server {
    listen 80;

    server_name cool-spot.ru www.cool-spot.ru;

    location /api/ {
        proxy_pass http://backend:8000;
    }

    location /admin/ {
        proxy_pass http://backend:8000;
    }

    location /media/ {
        alias /media/;
    }

    location / {
        proxy_pass http://frontend:80;
    }
}